language: c
compiler:
  - gcc

before_install:
    - git clone https://github.com/cpputest/cpputest ../cpputest
    - cd ../cpputest
    - ./configure
    - make
    - make install

before_script:
    - mkdir build/
    - cd build/
    - cmake ..
    - make

script: ./tests
